[`refurb`] Parenthesize lambda and ternary expressions in iter
Summary
--

Fixes #18590 by adding parentheses around lambdas and if expressions in `for`
loop iterators for FURB122 and FURB142. I also updated the docs on the helper
function to reflect the part actually being parenthesized and the new checks.

The `lambda` case actually causes a `TypeError` at runtime, but I think it's
still worth handling to avoid causing a syntax error.

```pycon
>>> s = set()
... for x in (1,) if True else (2,):
...     s.add(-x)
... for x in lambda: 0:
...     s.discard(-x)
...
Traceback (most recent call last):
  File "<python-input-0>", line 4, in <module>
    for x in lambda: 0:
             ^^^^^^^^^
TypeError: 'function' object is not iterable
```

Test Plan
--

New test cases based on the bug report