fix: method `red` not found in release builds
Release builds are currently failing with

```
   Compiling ruff_cli v0.0.254 (/home/rafal/test/ruff/crates/ruff_cli)
error[E0599]: no method named `red` found for reference `&'static str` in the current scope
  --> crates/ruff_cli/src/lib.rs:64:29
   |
64 |                     "error".red().bold(),
   |                             ^^^ method not found in `&'static str`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use colored::Colorize;
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ruff_cli` due to previous error
```

This PR adds the missing `colored::Colorize` import to the release build only panic hook handler in the CLI.