Remove invalid Python syntax from formatter tests
With the parser becoming a bit more strict, it discovered some invalid
syntax in one of the formatter tests. In particular, `yield a = 1`:

    >>> (yield a, b) = (1, 2)
      File "<input>", line 1
        (yield a, b) = (1, 2)
         ^^^^^^^^^^
    SyntaxError: cannot assign to yield expression here. Maybe you meant '==' instead of '='?

We just remove that bit from the `yield` test.