[ty] Add support for functional `Enum(...)` syntax (#23602)
## Summary
https://github.com/astral-sh/ty/issues/876
https://typing.python.org/en/latest/spec/enums.html#enum-definition

this pr implements the functional syntax for creating enums:
`Enum('Color2', 'RED, GREEN, BLUE')`

it mostly copies the `namedtuple` implementation

it supports the `start=` and `type=` kwargs for `Enum` as well
([docs](https://docs.python.org/3/library/enum.html#enum.EnumType.__call__))

it also supports `Flag` and `IntFlag`

the `ddtrace` diffs look to be correct - `IntEnum` call is now properly
recognized

###
for non-string-literal `name` arguments, it falls back to just returning
`type[Enum]` - this came up by way of a psycopg regression on this
[line](https://github.com/psycopg/psycopg/blob/eb87f0eb58ee05b7202b7d8835b925b084d32b5c/psycopg/psycopg/types/enum.py#L173)
- wasn't sure if this was better or worse than returning a
`DynamicEnumLiteral` with an unknown name and members.

this now looks correct for psycopg: `+
psycopg/psycopg/types/enum.py:173:12 [error] [invalid-return-type]
Return type does not match returned value: expected `Enum`, found
`type[Enum]``

however, it appears mypy does not correctly support the functional API
(i am wondering if this is why the psycopg typing is the way it is), or
maybe when just returning the result of the `Enum` call (without
assigning it to a name), it always assumes its looking up a member:

```python
from enum import Enum, EnumType
from typing import reveal_type


def make_color_1() -> EnumType:
    return Enum("Color1", names="RED GREEN")


def make_color_2() -> EnumType:
    return Enum("Color2", names=("RED", "GREEN"))


reveal_type(make_color_1())
reveal_type(make_color_2())
```

```bash
# mypy output

main.py:6: error: Incompatible return value type (got "Enum", expected "EnumMeta")  [return-value]
main.py:10: error: Incompatible return value type (got "Enum", expected "EnumMeta")  [return-value]
main.py:13: note: Revealed type is "enum.EnumMeta"
main.py:14: note: Revealed type is "enum.EnumMeta"
Found 2 errors in 1 file (checked 1 source file)

# runtime output
Runtime type is 'EnumType'
Runtime type is 'EnumType'
```

## Test Plan
mdtests

---------

Co-authored-by: Charlie Marsh <charlie.r.marsh@gmail.com>