[syntax-errors] Allow `yield` in base classes and annotations
Summary
--

This PR fixes the issue pointed out by @JelleZijlstra in
https://github.com/astral-sh/ruff/pull/17101#issuecomment-2777480204. Namely, I
conflated two very different errors from CPython:

```pycon
>>> def m[T](x: (yield from 1)): ...
  File "<python-input-310>", line 1
    def m[T](x: (yield from 1)): ...
                 ^^^^^^^^^^^^
SyntaxError: yield expression cannot be used within the definition of a generic
>>> def m(x: (yield from 1)): ...
  File "<python-input-311>", line 1
    def m(x: (yield from 1)): ...
              ^^^^^^^^^^^^
SyntaxError: 'yield from' outside function
>>> def outer():
...     def m(x: (yield from 1)): ...
...
>>>
```

I thought the second error was the same as the first, but `yield` (and `yield
from`) is actually valid in this position when inside a function scope. The same
is true for base classes, as pointed out in the original comment.

We don't currently raise an error for `yield` outside of a function, but that
should be handled separately.

On the upside, this had the benefit of removing the
`InvalidExpressionPosition::BaseClass` variant, the
`InvalidExpressionPosition::TypeAnnotation` variant, and the `allow_named_expr`
field from the visitor because they were all no longer used.

Test Plan
--

Updated inline tests.