[S507] fix doc recommended fix
paramiko set_missing_host_key_policy has mandatory positional arg
modify the documentation to set the policy to the default RejectPolicy

>>> from paramiko import client
>>> ssh_client = client.SSHClient()
>>> ssh_client.set_missing_host_key_policy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: SSHClient.set_missing_host_key_policy() missing 1 required positional argument: 'policy'

Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>