[syntax-errors] Invalid syntax in annotations
Summary
--

This PR detects the use of invalid syntax in annotation scopes, including
`yield` and `yield from` expressions and named expressions. I combined a few
different types of CPython errors here, but I think the resulting error messages
still make sense and are even preferable to what CPython gives. For example, we
report `yield expression cannot be used in a type annotation` for both of these:

```pycon
>>> def f[T](x: (yield 1)): ...
  File "<python-input-26>", line 1
    def f[T](x: (yield 1)): ...
                 ^^^^^^^
SyntaxError: yield expression cannot be used within the definition of a generic
>>> def foo() -> (yield x): ...
  File "<python-input-28>", line 1
    def foo() -> (yield x): ...
                  ^^^^^^^
SyntaxError: 'yield' outside function
```

Fixes #11118.

Test Plan
--

New inline tests, along with some updates to existing tests. I also combined the
`TestContext` code with the `SemanticSyntaxCheckerVisitor` because we now need
to set the `in_annotation` field on the context while visiting expressions.