Raise `ToolError` and exit non-zero on ecosystem panics
Summary
--

The huge number of changes in
https://github.com/astral-sh/ruff/pull/22205#issuecomment-3696660639 should have
obviously been a red flag, but I think it would be nice if CI failed when new
ecosystem panics were introduced. This PR adds a check for diagnostic lines that
start with `panic: Panicked at crates/`, raises a `ToolError` if any are found
in the results from the comparison executable, and then also exits non-zero if
any errors are returned.

If exiting non-zero is going too far, we could also just raise the `ToolError`,
as that will at least trigger this message, which was not the case on the
PLR1712 PR:

https://github.com/astral-sh/ruff/blob/f14edd8661e2803254f89265548c7487f47a09f6/python/ruff-ecosystem/ruff_ecosystem/check.py#L103-L106

Another option would be not to exit zero if Ruff panics, even if `--exit-zero`
is used, but I saw that ty has the same behavior and assumed that that was
intentional.

Test Plan
--

Local testing on the 0.15.3 tag showing that ruff-ecosystem exited non-zero. I
can also introduce a panic into a lint rule to test this in CI