Add message to formatter SyntaxError
**Summary** Add a static string error message to the formatter syntax error so we can disambiguate where the syntax error came from

**Test Plan** No fixed tests, we don't expect this to occur, but it helped with transformers syntax error debugging:

```
Error: Failed to format node

Caused by:
    syntax error: slice first colon token was not a colon
```