Fix ruff_dev repeat by removing short argument
This recently broke (i think with the cargo update?):

> thread 'main' panicked at 'Command repeat: Short option names must be unique for each argument, but '-n' is in use by both 'no_cache' and 'repeat''

This fixes this by removing the short argument