Propagate features
Summary
--

I ran into this earlier when trying to run

```shell
$ cargo test -p ruff_source_file --all-features
error[E0277]: the trait bound `TextSize: GetSize` is not satisfied
  --> crates/ruff_source_file/src/line_index.rs:23:41
```

It looks like we just needed to activate the `get-size` feature of
`ruff_text_size` when `ruff_source_file` activates its feature of the same name.

While I was at it, I ran this shell command to look for other cases with the
same problem:

```shell
for crate in crates/*; do
    if ! cargo test -p ${crate#*/} --all-features > /dev/null; then
        echo "$crate failed"
        break
    fi
done
```

and fixed those too. I also tried with no features enabled, since I know we've
run into similar problems with that before, but that didn't find anything except
for some unreachable `pub` warnings in for `TestDb` in `ty_project`. But
`TestDb` is conditionally re-exported, so I don't think we can get rid of those
warnings easily.

Should we consider throwing something like that into a daily/weekly cron job in
CI? I don't think we necessarily need to run it on every PR.

Test Plan
--

Same command above, which now works