[`pylint`] Detect `global` declarations in module scope (PLE0118)
Summary
--

While going through the syntax errors in [this comment], I was surprised to see
the error `name 'x' is assigned to before global declaration`, which corresponds
to [load-before-global-declaration (PLE0118)] and has also been reimplemented as
a syntax error (#17135). However, it looks like neither of the implementations
consider `global` declarations in the top-level module scope, which is a syntax
error in CPython:

```python
x = None
global x
```

```shell
> python -m compileall -f try.py
Compiling 'try.py'...
***   File "try.py", line 2
    global x
    ^^^^^^^^
SyntaxError: name 'x' is assigned to before global declaration
```

Test Plan
--

New PLE0118 test case.

We should also check the codspeed results carefully here. `Globals::from_body`
visits all of the statements in `body`, so this might be a really bad idea, but
it looked like the simplest fix.

[this comment]: https://github.com/astral-sh/ruff/issues/7633#issuecomment-1740424031
[load-before-global-declaration (PLE0118)]: https://docs.astral.sh/ruff/rules/load-before-global-declaration/#load-before-global-declaration-ple0118