Add support to write inline tests for the parser (#10681)
## Summary

This PR adds support to write inline tests for the parser.

Inline tests are defined in the Rust code itself. The test are written
through comments of a specific form:
```rs
// test this_is_the_test_name
// def foo():
//     pass
println!("some rust code");

// test_err this_test_should_raise_syntax_err
// [1, 2
println!("some rust code");
```

This way it's easier to reason about a specific code in the parser and
the tests are used both as an example and a way to test that logic.

This code runs as an integration tests which fails in the following
cases:
1. When there are test comments but no corresponding test files

	```
	running 1 test
	Error: Following files were not up-to date and has been updated:

crates/ruff_python_parser/resources/inline/ok/slice_single_starred_element.py
	  crates/ruff_python_parser/resources/inline/ok/slice_single_element.py
	Re-run the tests with `cargo test`
	
	test generate_inline_tests ... FAILED
	```

2. When there are test files but no corresponding test comments

	```
	running 1 test
	Error: Unreferenced test files found for which no comment exists:
	  crates/ruff_python_parser/resources/inline/ok/slice_single_element.py

crates/ruff_python_parser/resources/inline/ok/slice_single_starred_element.py
	
	test generate_inline_tests ... FAILED
	```

3. When there are multiple tests with the same name

	```
	running 1 test
Error: Duplicate test found: "slice_single_element" (search '// test
slice_single_element' for the location)

	test generate_inline_tests ... FAILED
	```

## References:

- `rust-analyzer`:
https://github.com/rust-lang/rust-analyzer/blob/e4a405f877efd820bef9c0e77a02494e47c17512/crates/parser/src/tests/sourcegen_inline_tests.rs
- `biome`:
https://github.com/biomejs/biome/blob/b9f8ffea9967b098ec4c8bf74fa96826a879f043/xtask/codegen/src/parser_tests.rs

## Test Plan

Using the below code:
```rs
// test slice_single_starred_element
// x[*y]

// test slice_single_element
// x[y]
```

Run the new tests with:
```
cargo test --package ruff_python_parser --test generate_inline_tests
```