Fix exception handler parenthesis removal for Python 3.14+
Summary
--

Fixes #23125. We were missing handling for starred elements within a tuple of
exceptions. This produces valid syntax but changes the AST from a
non-starred `except` handler to a starred `except` handler (which can be invalid
if there are other non-starred handlers):

```py
try: ...
except (*exceptions, ValueError): ...

try: ...
except *exceptions, ValueError: ...
```

Starred expressions in other positions are outright invalid:

```pycon
>>> try: ...
... except Exception, *exceptions: ...
...
  File "<python-input-8>", line 2
    except Exception, *exceptions: ...
                      ^
SyntaxError: invalid syntax
```

We now preserve parentheses in these cases as well.

Test Plan
--

New tests derived from the issue